Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,12 +26,10 @@ jobs:
           jq -S . "$file" > "$file.dftmp"
           if ! diff "$file" "$file.dftmp"; then
             mv "$file.dftmp" "$file"
-            echo "CHANGES $file"
+            echo "CHANGES to $file"
             echo "CHANGES=true" >> "$GITHUB_ENV"
           else
             echo "no changes $file"
-            cat $file
-            cat $file.dftmp
             rm "$file.dftmp"
           fi
         done
@@ -41,9 +39,7 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
       run: |
-        env
         git config --global --add safe.directory $GITHUB_WORKSPACE
-        git status --porcelain
         if [ -n "$(git status --porcelain)" ]; then
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
@@ -51,5 +47,6 @@ jobs:
           git commit -m "Sort JSON files $(date +%F)"
           git push origin HEAD
         else
-          echo "No sorting changes to commit."
+          echo "ERROR: Unable to find changes to commit."
+          exit 1
         fi
